### PR TITLE
Support Rails 5 in gemspec

### PR DESCRIPTION
**Pull request by dgilperez**
I haven't tested in a live app (yet), but tests are green. I'm testing it in a couple of days in a real app, you can wait to merge if you want some feedback. Related: #13 

Thanks!

### CODE REVIEW

**Comment by amiel** [comment]
Yes, thanks for the PR. I'll wait until I hear back to make sure everything works on your end.

I'll work on getting CI fixed when I get a chance.

**Comment by amiel** [comment]
@dgilperez CI is fixed in master. Once you get a chance to verify that everything works, please rebase on master and I will merge.

Thanks for working on this :)

**Comment by dgilperez** [comment]
Done! 

I've the code working in production with no hiccups.

**Comment by amiel** [comment]
Great, thanks so much for testing!

Would you be willing to rebase real quick so CI can re-run?

**Comment by dgilperez** [comment]
I rebased already

**Comment by amiel** [comment]
Ah, ok. I guess I need to update the ruby version on CI.

**Comment by amiel** [comment]
@dgilperez all merged, thanks

0.4.0 has been released with this change

**Pull request merged**
